version: "3.9"

services:
#  server:
#    container_name: server
#    build:
#      context: .
#      args:
#        LOCAL: "true"
#    env_file:
#      - .env
#    ports:
#      - "8080:8080"
#    volumes:
#      - .:/usr/src/app
#    depends_on:
#      - postgres
#      - nats-streaming

  postgres:
    image: postgres
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST: ${DB_HOST}
    volumes:
      - data-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nats-streaming:
    image: nats-streaming:latest
    container_name: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
    command:
      - "--cluster_id"
      - "test-cluster"

volumes:
  data-db: